### ISSUE TITLE
Add disabled states for input[type='email'], input[type='text'], input[type='password']

### ISSUE THREAD

**Issue by lwkchan** [jdan/98.css#109]
Hello 👋
Using 98.css in my own project at the moment and I would like to add disabled input[type="text"]. Basing it off this image I found, I think adding a silver background is enough. Something like

```css
input[type='email']:disabled,
input[type='password']:disabled,
input[type='text']:disabled {
  background-color: var(--surface);
}
```

![windows 98 form example](https://techgenix.com/content/wn/img/gifs/w98first.gif)
