### ISSUE TITLE
Active tab doesn't have dotted line

### ISSUE THREAD

**Issue by juanigaray** [jdan/98.css#175]
It is however implemented for the *focused* tab:

```css
menu[role=tablist]>li>a:focus {
    outline: 1px dotted #222;
}
```

We should just add the `:active` selector.
