### ISSUE TITLE
Feature request: forced active state for buttons

### ISSUE THREAD

**Issue by brandongregoryscott** [jdan/98.css#215]
Hi there! I love the project and I'm planning to use it in a project I'm working on. One thing that I would love to have is the ability to explicitly render a button in an `:active` state. There's an example of this in the docs, but it's not clear how this is being done. (The code just shows a `<button>` element without any attributes)

<img width="840" alt="Image" src="https://github.com/user-attachments/assets/7d8bb214-26ee-4507-8cd4-ab970e6d1a4b" />

I think it would be pretty easy to support with a data attribute selector, like `button[data-active]: { ... sunken styles }`

**Comment by ale-rinaldi** [comment]
An official support would be nice; meanwhile you can use the same trick the documentation uses by putting something like this in your own CSS:

```css
button.active {
  box-shadow: inset -1px -1px #ffffff, inset 1px 1px #0a0a0a,
    inset -2px -2px #dfdfdf, inset 2px 2px #808080;
}
```

and then using a `<button class="active">`
