### ISSUE TITLE
What's the common wisdom on build/ + checking in builds?

### ISSUE THREAD

**Issue by jdan** [jdan/98.css#53]
As many of you noticed, `build/98.css` and `docs/98.css` are checked in. `docs/` powers https://jdan.github.io/98.css, and `build/` allows folks to use 98.css via https://unpkg.com/98.css

However, these are annoying to deal with in PRs! They're minified so we get conflicts on pretty much every commit. I used to have an `npm test` (+ travis integration) to make sure people ran `npm run build`, but I've just removed that. I'm starting to think we _don't_ want any PRs to include `build/98.css` or `docs/98.css`.

Any ideas for making this more pleasant?

**Comment by jamesorlakin** [comment]
I think in an ideal world you would separate your releases from the primary source code, but obviously this involves some legwork and trickery.

For any commit on master or tag, Travis could:
- Build the release
- Publish the build to npm as a new version to get on unpkg.
- Create a commit with the build in and (force-push) it to the `gh-pages` branch to update jdan.github.io
- Create a GitHub release with a zipped up built package? A tag by default becomes a release with the zipped source code.

**Comment by jdan** [comment]
I was able to get `build/` out of version control - after chatting with @kennygoff I realized I could still publish it to npm! https://unpkg.com/98.css@0.1.6/dist/98.css. This should remove a _lot_ of noise in future PRs. I'll see if I need a `postinstall` script in the future or something but I bet this'll work fine.

As for docs... I moved things into `npm run build:docs` but it still feels a _little_ weird that PRs will contain changes to `docs/98.css`. It seems like there should be an `npm start` which builds and serves `style.css` and `docs/index.html.ejs` but does not actually change `docs/98.css`.

**Comment by WesleyKlop** [comment]
You can use github actions to build the docs and commit it to a specific branch (like github pages)
Did that myself like this (for storybook but process should be the same):

```yaml
name: deploy storybook

on:
    push:
        branches:
            - master

jobs:
    deploy-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2 # Checkout repo
            - uses: actions/setup-node@v1 # Setup node (optional)
              with:
                  node-version: '13.x'
            - id: yarn-cache-dir-path # Find cache dir, there's an equivalent for npm, just google it
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v1 # Load cache
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn --frozen-lockfile # Install deps
            - run: yarn storybook:build # Build storybook (or the docs in your case)
            - uses: JamesIves/github-pages-deploy-action@releases/v3 # Deploy to gh-pages branch
              with:
                  GITHUB_TOKEN: ${{ github.token }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: storybook-static # The folder the action should deploy.
                  CLEAN: true
```
